spring.application.name=frontend
server.port=8080
logging.level.org.atmosphere=warn
spring.mustache.check-template-location=false

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Vaadin
#vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,com.example.application
#vaadin.frontend.hotdeploy=true