services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - app-net

  backend:
    build:
      context: ./Monopoly-Logic
    image: zamatalo/monopoly-test:backend-latest
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
      database:
         condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/postgres"
    networks:
      - app-net

  api-gateway:
    build:
      context: ./Monopoly-API-Gateway/
    image: zamatalo/monopoly-test:api-gateway-latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    depends_on:
      redis:
          condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-net

  ui:
    build:
      context: ./monopoly-ui2
    image: zamatalo/monopoly-test:ui-latest
    ports:
      - "80:80"
    networks:
      - app-net
    environment:
      GATEWAY_HOST: api-gateway
    restart: unless-stopped

  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-net

  dice-server:
    build:
      context: ./Monopoly-Dice/
    image: zamatalo/monopoly-test:dice-server-latest
    container_name: dice-server
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
