server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000
spring.data.redis.gameRequestStream=game.request
spring.data.redis.gameResponseStream=game.response
spring.data.redis.diceRollChannel=""
spring.data.redis.backendGroup=backend
spring.data.redis.gatewayGroup=gateway

#Debug
logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.data.redis=DEBUG
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always