server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#Graphql
spring.graphql.path=/api/v1/graphql
#spring.graphql.graphiql.enabled=true
spring.graphql.websocket.path=/api/v1/graphql
