type Mutation {
    rollDice(gameId: ID!, playerId: ID!): Int
    joinToGame(gameId: ID!, playerName: String!,playerColor:PlayerColors!,playerId:ID!):GameDTO!
    createNewGame:GameDTO
    buyPropertyForPlayer(gameId:ID!,playerId:ID!):PropertyDTO
#    makePlayerAction(gameId:ID!,playerId:ID!,action:PlayerActions!):String
#    makeGameAction(gameId:ID!,action:GameActions!):String
    startGame(gameId:ID!):GameDTO
    addBotToGame(gameId:ID!):GameDTO
    endTurn(gameId:ID,playerId:ID):GameDTO
    resolveSpecialTile(gameId:ID!,playerId:ID!):SpecialTileData
}

