enum GameState {
    STARTED
    IN_PROGRESS
    FINISHED
}

enum PlayerColors {
    PLAYER_RED,
    PLAYER_BLUE,
    PLAYER_YELLOW,
    PLAYER_GREEN
}

enum PropertyNames{
    SHOULD_BE_ADDED
}

type Game {
    gameId: ID!
    players: [Player]
    currentPlayerIndex:Int!
    gameState: GameState
}

type Player {
    playerId: ID
    color: PlayerColors
    balance: Int
    position: Int
    ownedProperties: [Property]
}

type Property{
    propertyName:PropertyNames
    cost: Int
    rent:Int
    upgradable: Boolean
}

type Subscription {
    gameUpdated(gameId: ID!): Game
}
