enum GameState {
    STARTED
    IN_PROGRESS
    FINISHED
}

enum PlayerColors {
    PLAYER_RED,
    PLAYER_BLUE,
    PLAYER_YELLOW,
    PLAYER_GREEN
}

enum PropertyNames{
    SHOULD_BE_ADDED
}

type GameDTO {
    gameId: ID!
    players: [PlayerDTO]
    currentPlayerIndex:Int!
    gameState: GameState
}

type PlayerDTO {
    playerId: ID
    color: PlayerColors
    balance: Int
    position: Int
    ownedProperties: [PropertyDTO]
}

type PropertyDTO{
    propertyName:PropertyNames
    cost: Int
    rent:Int
    upgradable: Boolean
}


