type GameDTO {
    gameId: ID
    players: [PlayerDTO]
    currentPlayerIndex: Int
    gameState: GameState
    createdTime: String
    gameActions:[GameActions]
}

type PlayerDTO {
    playerId: ID
    playerName: String
    color: PlayerColors
    balance: Int
    position: Int
    inJail_Turns: Int
    isBot:Boolean
    playerState:PlayerState
    playerActions:[PlayerActions]
    ownedProperties: [PropertyDTO]
}

type PropertyDTO {
    displayName: String
    boardPosition: Int
    isOwned:Boolean
    cost: Int
    upgradable: Boolean
}

