server.port=8083

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000
spring.data.redis.gameRequestStream=game.request
spring.data.redis.gameResponseStream=game.response
spring.data.redis.gameUpdateChannel=game.gameUpdate
spring.data.redis.diceUpdateChannel=game.diceUpdate
spring.data.redis.diceRollChannel=""
spring.data.redis.backendGroup=backend
spring.data.redis.gatewayGroup=gateway


#Graphql
spring.graphql.http.path=/api/v1/graphql
spring.graphql.graphiql.enabled=false
spring.graphql.websocket.path=/api/v1/graphql
spring.graphql.schema.locations=classpath:/schema/graphql/
spring.graphql.schema.file-extensions=.graphqls,.gqls
spring.graphql.schema.inspection.enabled=true
spring.graphql.schema.introspection.enabled=true
spring.graphql.schema.printer.enabled=true
spring.graphql.websocket.keep-alive=15000


#Debug
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.graphql=DEBUG