server.port=8083


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000


#Graphql
spring.graphql.path=/api/v1/graphql
spring.graphql.graphiql.enabled=false
spring.graphql.websocket.path=/api/v1/graphql
spring.graphql.schema.locations=classpath:/schema/graphql/
spring.graphql.schema.printer.enabled=true

spring.websocket.session.timeout=30000
spring.graphql.websocket.connection-timeout=30000
spring.graphql.websocket.keep-alive=15000
