#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: graphql-subscription
#          uri: ws://localhost:8082 # the GraphQL microservice that handles subscriptions
#          predicates:
#            - Path=/subscriptions/**
#          filters:
#            - RewritePath=/subscriptions/(?<segment>.*), /${segment}
